# Generated by Django 3.0.8 on 2020-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=2)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
