# Generated by Django 3.0.8 on 2020-11-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(help_text='choose the specialist', max_length=100)),
                ('date_appointment', models.DateTimeField(help_text='choose the date appointment')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_email', to='accounts.UserProfile')),
            ],
        ),
    ]
