# Generated by Django 3.0.8 on 2020-12-09 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userappointment_date_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='email address', max_length=255, unique=True, verbose_name='email address')),
                ('phone_number', models.DecimalField(decimal_places=0, help_text='telephone number', max_digits=11, unique=True, verbose_name='telephone number')),
                ('first_name', models.CharField(help_text='first name', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='last name', max_length=100, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userappointment',
            name='date_appointment',
            field=models.DateTimeField(auto_now=True, help_text='choose the date appointment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='add_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture before'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='choose the gender', max_length=6),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='specialist',
            field=models.CharField(choices=[('С', 'Сosmetologist'), ('D', 'Dermatologist')], help_text='choose the specialist', max_length=20),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
