# Generated by Django 3.0.8 on 2020-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201209_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='date_appointment',
            field=models.DateTimeField(help_text='choose the date appointment'),
        ),
    ]
