# Generated by Django 3.1.4 on 2020-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201209_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='specialist',
            field=models.CharField(choices=[('СI', 'Сosmetologist Ivanov'), ('DA', 'Dermatologist Andreev'), ('DV', 'Dermatologist Vasilyev'), ('CA', 'Сosmetologist Antonov')], help_text='choose the specialist', max_length=20),
        ),
    ]
