# Generated by Django 3.1.4 on 2021-04-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210422_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
