# Generated by Django 3.1.4 on 2021-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210423_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(help_text='Изображение должно иметь разрешение не ниже разрешения', null=True, upload_to='photos/', verbose_name='Ваше фото (min=768x768, max=4000x4000)'),
        ),
    ]
