# Generated by Django 3.1.4 on 2021-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210425_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
