# Generated by Django 3.1.4 on 2021-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210425_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\user\\Desktop\\Python_Learning\\Projects\\estem2\\src\\photos'),
        ),
    ]
