# Generated by Django 3.1.4 on 2021-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='photos'),
        ),
    ]
